const fs = require('fs-extra')
fs.copy('./dist/css', './dist/prerendered/css')
    .then(() => console.log('success!'))
    .catch(err => console.error(err))
fs.copy('./dist/img', './dist/prerendered/img')
    .then(() => console.log('success!'))
    .catch(err => console.error(err))
fs.copy('./dist/js', './dist/prerendered/js')
    .then(() => console.log('success!'))
    .catch(err => console.error(err))